<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>NeuralFlow</AssemblyName>
    <RootNamespace>NeuralFlow</RootNamespace>
    <Version>0.6.0</Version>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
  </PropertyGroup>
  <ItemGroup><None Include="../product.json" Link="product.json" CopyToOutputDirectory="PreserveNewest" /></ItemGroup>
</Project>
